
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tksml
 */
public class ERP_Goods extends javax.swing.JFrame {
    static javax.swing.JFrame User;
    static javax.swing.JFrame Salary;
    static javax.swing.JFrame Transaction;
    static javax.swing.JFrame Goods;
    static javax.swing.JFrame Order;
    DBMan DBM = new DBMan();
    String strSQL = "Select * From Goods ";
    int iCntRow = 0;
    ArrayList pay = new ArrayList();
    SimpleDateFormat format = new SimpleDateFormat ( "yyyyMMdd");
		
    Date time1 = new Date();
		
    String time = format.format(time1);
    /**
     * Creates new form ERP
     */
    public ERP_Goods() {
        initComponents();
        try{
            DBM.dbOpen();
            setTableAssetsDB(strSQL);
            DBM.dbClose();
        }catch (Exception e){
            System.out.println("SQLException: "+ e.getMessage());
        }
    }
//    public void getDBData(String strQuery){
//        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
//        model.setNumRows(0);
//        model.setNumRows(31);
//        iCntRow = 0;
//        try{
//            DBM.DB_rs = DBM.DB_stmt.executeQuery(strQuery);
//            while(DBM.DB_rs.next()){
//                jTable1.setValueAt(DBM.DB_rs.getString("Goods_code"), iCntRow, 0);
//                jTable1.setValueAt(DBM.DB_rs.getString("Goods_name"), iCntRow, 1);
//                jTable1.setValueAt(DBM.DB_rs.getString("Goods_price"), iCntRow, 2);
//                jTable1.setValueAt(DBM.DB_rs.getString("Goods_stock"), iCntRow, 3);
//                iCntRow++;
//            }
//            DBM.DB_rs.close();
//        }catch (Exception e){
//            System.out.println("SQLException: "+ e.getMessage());
//        }
//    }
    
    public void setTableAssetsDB(String strQuery) {
        DefaultTableModel modelAsset = (DefaultTableModel)tableAssets.getModel();
        modelAsset.setNumRows(0);
        String assetsSQL = "select purchase_num, capital, asset.goods_code, goods_name, purchase_amount, purchase_amount-goods_changed_price, goods_changed_price, goods_stock, purchase_date\n" +
"from asset, goods where asset.goods_code = goods.goods_code";
        try{
            DBM.DB_rs = DBM.DB_stmt.executeQuery(assetsSQL);
            while(DBM.DB_rs.next()) {
                if(!DBM.DB_rs.getString("goods_code").equals(null)){
                    Vector myVC = new Vector();
                    myVC.addElement(DBM.DB_rs.getString("purchase_num"));
                    myVC.addElement(DBM.DB_rs.getString("goods_code"));
                    myVC.addElement(DBM.DB_rs.getString("goods_name"));
                    myVC.addElement(DBM.DB_rs.getString("purchase_amount"));
                    myVC.addElement(DBM.DB_rs.getString("purchase_amount-goods_changed_price"));
                    myVC.addElement(DBM.DB_rs.getString("goods_changed_price"));
                    myVC.addElement(DBM.DB_rs.getString("goods_stock"));
                    myVC.addElement(DBM.DB_rs.getString("purchase_date"));
                    modelAsset.addRow(myVC);
                    labelCapitalResult.setText(DBM.DB_rs.getString("capital"));
                }
            }
            DBM.DB_rs.close();
        } catch(Exception e) {
            System.out.println("SQLException : " + e.getMessage());
        }
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tableAssets.getModel());
        tableAssets.setRowSorter(sorter);
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
 
        int columnIndexToSort = 0;
        sortKeys.add(new RowSorter.SortKey(columnIndexToSort, SortOrder.DESCENDING));
 
        sorter.setSortKeys(sortKeys);
        sorter.sort();
        
        for(int idx = 0; idx < tableAssets.getRowCount(); idx++) {
            if(tableAssets.getValueAt(idx, 0) != null)
                tableAssets.setValueAt(idx+1, idx, 0);
            else
                break;
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbtnSal = new javax.swing.JRadioButton();
        rbtnTrans = new javax.swing.JRadioButton();
        rbtnEmp = new javax.swing.JRadioButton();
        rbtnGoods = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableAssets = new javax.swing.JTable();
        labelCapital = new javax.swing.JLabel();
        labelAsset = new javax.swing.JLabel();
        labelCapitalResult = new javax.swing.JLabel();
        btnRefreshAsset = new javax.swing.JButton();
        rbtnExpenses = new javax.swing.JRadioButton();
        rbtnPS = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jLabel9.setText("자산관리 테이블");

        buttonGroup1.add(rbtnSal);
        rbtnSal.setText("급여");
        rbtnSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnTrans);
        rbtnTrans.setText("거래");
        rbtnTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTransActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnEmp);
        rbtnEmp.setText("사원");
        rbtnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEmpActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnGoods);
        rbtnGoods.setText("상품");
        rbtnGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGoodsActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("발주");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        tableAssets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "번호", "상품코드", "상품명", "상품원가", "상품현재가격", "감가상각", "수량", "구입일자"
            }
        ));
        jScrollPane4.setViewportView(tableAssets);

        labelCapital.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N
        labelCapital.setText("현재 자본금");

        labelAsset.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N
        labelAsset.setText("자산");

        labelCapitalResult.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N

        btnRefreshAsset.setText("새로고침");
        btnRefreshAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshAssetActionPerformed(evt);
            }
        });

        rbtnExpenses.setText("지출");
        rbtnExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnExpensesActionPerformed(evt);
            }
        });

        rbtnPS.setText("구매/판매");
        rbtnPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPSActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(396, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rbtnEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnSal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnTrans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnGoods)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnPS, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelAsset)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelCapital)
                                    .addGap(44, 44, 44)
                                    .addComponent(labelCapitalResult, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                            .addComponent(btnRefreshAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnSal)
                    .addComponent(rbtnTrans)
                    .addComponent(rbtnEmp)
                    .addComponent(rbtnGoods)
                    .addComponent(jRadioButton1)
                    .addComponent(rbtnExpenses)
                    .addComponent(rbtnPS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(444, 444, 444)
                .addComponent(jLabel5)
                .addContainerGap(498, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRefreshAsset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCapitalResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCapital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(54, 54, 54)
                    .addComponent(labelAsset)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addGap(67, 67, 67)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSalActionPerformed
        Login1.User.setVisible(false);
        Login1.Salary.setVisible(true);
        Login1.Transaction.setVisible(false);
        Login1.Goods.setVisible(false);
        Login1.Order.setVisible(false);
        Login1.PS.setVisible(false);
        Login1.Expenses.setVisible(false);
    }//GEN-LAST:event_rbtnSalActionPerformed

    private void rbtnTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTransActionPerformed
        Login1.User.setVisible(false);
        Login1.Salary.setVisible(false);
        Login1.Transaction.setVisible(true);
        Login1.Goods.setVisible(false);
        Login1.Order.setVisible(false);
        Login1.PS.setVisible(false);
        Login1.Expenses.setVisible(false);
    }//GEN-LAST:event_rbtnTransActionPerformed

    private void rbtnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEmpActionPerformed
        Login1.User.setVisible(true);
        Login1.Salary.setVisible(false);
        Login1.Transaction.setVisible(false);
        Login1.Goods.setVisible(false);
        Login1.Order.setVisible(false);
        Login1.PS.setVisible(false);
        Login1.Expenses.setVisible(false);
    }//GEN-LAST:event_rbtnEmpActionPerformed

    private void rbtnGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGoodsActionPerformed
        Login1.User.setVisible(false);
        Login1.Salary.setVisible(false);
        Login1.Transaction.setVisible(false);
        Login1.Goods.setVisible(true);
        Login1.Order.setVisible(false);
        Login1.PS.setVisible(false);
        Login1.Expenses.setVisible(false);
    }//GEN-LAST:event_rbtnGoodsActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        Login1.User.setVisible(false);
        Login1.Salary.setVisible(false);
        Login1.Transaction.setVisible(false);
        Login1.Goods.setVisible(false);
        Login1.Order.setVisible(true);
        Login1.PS.setVisible(false);
        Login1.Expenses.setVisible(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void btnRefreshAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshAssetActionPerformed
        // TODO add your handling code here:
        try {
            DBM.dbOpen();
            setTableAssetsDB(strSQL);
            DBM.dbClose();
        } catch (Exception e) {
            System.out.println("SQLException : " + e.getMessage());
        }
    }//GEN-LAST:event_btnRefreshAssetActionPerformed

    private void rbtnExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnExpensesActionPerformed
        // TODO add your handling code here:
        Login1.User.setVisible(false);
        Login1.Salary.setVisible(false);
        Login1.Transaction.setVisible(false);
        Login1.Goods.setVisible(false);
        Login1.Order.setVisible(false);
        Login1.PS.setVisible(false);
        Login1.Expenses.setVisible(true);
    }//GEN-LAST:event_rbtnExpensesActionPerformed

    private void rbtnPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPSActionPerformed
        // TODO add your handling code here:
        Login1.User.setVisible(false);
        Login1.Salary.setVisible(false);
        Login1.Transaction.setVisible(false);
        Login1.Goods.setVisible(false);
        Login1.Order.setVisible(false);
        Login1.PS.setVisible(true);
        Login1.Expenses.setVisible(false);
    }//GEN-LAST:event_rbtnPSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ERP_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ERP_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ERP_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ERP_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User = new ERP_User();
                Salary = new ERP_Salary();
                Transaction = new ERP_Transaction();
                Goods = new ERP_Goods();
                User.setVisible(false);
                Salary.setVisible(false);
                Transaction.setVisible(false);
                Goods.setVisible(true);
                Order = new ERP_Order();
                Order.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshAsset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelAsset;
    private javax.swing.JLabel labelCapital;
    private javax.swing.JLabel labelCapitalResult;
    private javax.swing.JRadioButton rbtnEmp;
    private javax.swing.JRadioButton rbtnExpenses;
    private javax.swing.JRadioButton rbtnGoods;
    private javax.swing.JRadioButton rbtnPS;
    private javax.swing.JRadioButton rbtnSal;
    private javax.swing.JRadioButton rbtnTrans;
    private javax.swing.JTable tableAssets;
    // End of variables declaration//GEN-END:variables
}
