
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tksml
 */
public class ERP_Expenses extends javax.swing.JFrame {
    static javax.swing.JFrame User;
    static javax.swing.JFrame Salary;
    static javax.swing.JFrame Transaction;
    static javax.swing.JFrame Goods;
    static javax.swing.JFrame Order;
    DBMan DBM = new DBMan();
    String strSQL = "Select * From Goods ";
    int iCntRow = 0;
    ArrayList pay = new ArrayList();
    SimpleDateFormat format = new SimpleDateFormat ( "yyyyMMdd");
		
    Date time1 = new Date();
		
    String time = format.format(time1);
    /**
     * Creates new form ERP
     */
    public ERP_Expenses() {
        initComponents();
        try{
            DBM.dbOpen();
            setTableExpensesDB(strSQL);
            DBM.dbClose();
        }catch (Exception e){
            System.out.println("SQLException: "+ e.getMessage());
        }
    }
//    public void getDBData(String strQuery){
//        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
//        model.setNumRows(0);
//        model.setNumRows(31);
//        iCntRow = 0;
//        try{
//            DBM.DB_rs = DBM.DB_stmt.executeQuery(strQuery);
//            while(DBM.DB_rs.next()){
//                jTable1.setValueAt(DBM.DB_rs.getString("Goods_code"), iCntRow, 0);
//                jTable1.setValueAt(DBM.DB_rs.getString("Goods_name"), iCntRow, 1);
//                jTable1.setValueAt(DBM.DB_rs.getString("Goods_price"), iCntRow, 2);
//                jTable1.setValueAt(DBM.DB_rs.getString("Goods_stock"), iCntRow, 3);
//                iCntRow++;
//            }
//            DBM.DB_rs.close();
//        }catch (Exception e){
//            System.out.println("SQLException: "+ e.getMessage());
//        }
//    }
   
    public void setTableExpensesDB(String strQuery) {
        DefaultTableModel modelAsset = (DefaultTableModel)tableExpenses.getModel();
        modelAsset.setNumRows(0);
        String ExpensesSQL = "select * from expenses";
        try{
            DBM.DB_rs = DBM.DB_stmt.executeQuery(ExpensesSQL);
            while(DBM.DB_rs.next()) {
                    Vector myVC = new Vector();
                    myVC.addElement(DBM.DB_rs.getString("expenses_no"));
                    myVC.addElement(DBM.DB_rs.getString("expenses_code"));
                    myVC.addElement(DBM.DB_rs.getString("expenses_name"));
                    myVC.addElement(DBM.DB_rs.getString("expenses_date"));
                    myVC.addElement(DBM.DB_rs.getString("expenses_cost"));
                    myVC.addElement(DBM.DB_rs.getString("expenses_account"));
                    myVC.addElement(DBM.DB_rs.getString("expenses_remark"));
                    modelAsset.addRow(myVC);
            }
            DBM.DB_rs.close();
        } catch(Exception e) {
            System.out.println("SQLException : " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbtnSal = new javax.swing.JRadioButton();
        rbtnTrans = new javax.swing.JRadioButton();
        rbtnEmp = new javax.swing.JRadioButton();
        rbtnGoods = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        labelExpensesName = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableExpenses = new javax.swing.JTable();
        labelExpensesCost = new javax.swing.JLabel();
        labelExpensesRemark = new javax.swing.JLabel();
        txtExpensesCost = new javax.swing.JTextField();
        txtExpensesRemark = new javax.swing.JTextField();
        txtExpensesCode = new javax.swing.JTextField();
        txtExpensesName = new javax.swing.JTextField();
        btnRefreshExpenses = new javax.swing.JButton();
        txtExpensesAccount = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnFilleSave = new javax.swing.JButton();
        labelExpensesNo = new javax.swing.JLabel();
        labelExpensesCode = new javax.swing.JLabel();
        rbtnExpenses = new javax.swing.JRadioButton();
        rbtnPS = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jLabel9.setText("지출관리 테이블");

        buttonGroup1.add(rbtnSal);
        rbtnSal.setText("급여");
        rbtnSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnTrans);
        rbtnTrans.setText("거래");
        rbtnTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTransActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnEmp);
        rbtnEmp.setText("사원");
        rbtnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEmpActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnGoods);
        rbtnGoods.setText("상품");
        rbtnGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGoodsActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("발주");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        labelExpensesName.setText("거래처명");

        tableExpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "번호", "비용코드", "비용명", "날짜", "금액", "거래처명", "비고"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tableExpenses);

        labelExpensesCost.setText("금액");

        labelExpensesRemark.setText("비고");

        btnRefreshExpenses.setText("새로고침");
        btnRefreshExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshExpensesActionPerformed(evt);
            }
        });

        btnOK.setText("확인");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnFilleSave.setText("파일저장");
        btnFilleSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilleSaveActionPerformed(evt);
            }
        });

        labelExpensesNo.setText("비용코드");

        labelExpensesCode.setText("비용명");

        rbtnExpenses.setText("지출");
        rbtnExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnExpensesActionPerformed(evt);
            }
        });

        rbtnPS.setText("구매/판매");
        rbtnPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPSActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelExpensesCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelExpensesName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelExpensesCost, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelExpensesNo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelExpensesRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtExpensesRemark)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtExpensesCode)
                                        .addComponent(txtExpensesName)
                                        .addComponent(txtExpensesAccount)
                                        .addComponent(txtExpensesCost, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFilleSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRefreshExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnSal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnTrans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnGoods)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnPS, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnSal)
                    .addComponent(rbtnTrans)
                    .addComponent(rbtnEmp)
                    .addComponent(rbtnGoods)
                    .addComponent(jRadioButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnExpenses)
                        .addComponent(rbtnPS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtExpensesCode)
                    .addComponent(labelExpensesNo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFilleSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtExpensesName)
                    .addComponent(labelExpensesCode, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRefreshExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelExpensesName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExpensesAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelExpensesCost, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExpensesCost, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelExpensesRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExpensesRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSalActionPerformed
        Login1.User.setVisible(false);
        Login1.Salary.setVisible(true);
        Login1.Transaction.setVisible(false);
        Login1.Goods.setVisible(false);
        Login1.Order.setVisible(false);
        Login1.PS.setVisible(false);
        Login1.Expenses.setVisible(false);
    }//GEN-LAST:event_rbtnSalActionPerformed

    private void rbtnTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTransActionPerformed
        Login1.User.setVisible(false);
        Login1.Salary.setVisible(false);
        Login1.Transaction.setVisible(true);
        Login1.Goods.setVisible(false);
        Login1.Order.setVisible(false);
        Login1.PS.setVisible(false);
        Login1.Expenses.setVisible(false);
    }//GEN-LAST:event_rbtnTransActionPerformed

    private void rbtnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEmpActionPerformed
        Login1.User.setVisible(true);
        Login1.Salary.setVisible(false);
        Login1.Transaction.setVisible(false);
        Login1.Goods.setVisible(false);
        Login1.Order.setVisible(false);
        Login1.PS.setVisible(false);
        Login1.Expenses.setVisible(false);
    }//GEN-LAST:event_rbtnEmpActionPerformed

    private void rbtnGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGoodsActionPerformed
        Login1.User.setVisible(false);
        Login1.Salary.setVisible(false);
        Login1.Transaction.setVisible(false);
        Login1.Goods.setVisible(true);
        Login1.Order.setVisible(false);
        Login1.PS.setVisible(false);
        Login1.Expenses.setVisible(false);
    }//GEN-LAST:event_rbtnGoodsActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        Login1.User.setVisible(false);
        Login1.Salary.setVisible(false);
        Login1.Transaction.setVisible(false);
        Login1.Goods.setVisible(false);
        Login1.Order.setVisible(true);
        Login1.PS.setVisible(false);
        Login1.Expenses.setVisible(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void btnRefreshExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshExpensesActionPerformed
        // TODO add your handling code here:
        try {
            DBM.dbOpen();
            setTableExpensesDB(strSQL);
            DBM.dbClose();
        } catch (Exception e) {
            System.out.println("SQLException : " + e.getMessage());
        }
    }//GEN-LAST:event_btnRefreshExpensesActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        int dateTime = Integer.parseInt(time);
        try {
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery("select * from expenses");
            System.out.println("1");
            int count = 0;
            while(DBM.DB_rs.next()){
                count = DBM.DB_rs.getInt("expenses_no")+1;
            }

            String strExpensesSQL = "Insert Into expenses Values (" + count + "," + txtExpensesCode.getText() + ", '" + txtExpensesName.getText() + "', " + dateTime + ", '" + txtExpensesAccount.getText() + "', " + txtExpensesCost.getText() + ", '" + txtExpensesRemark.getText() + "')";
            DBM.DB_stmt.executeUpdate(strExpensesSQL);
            DBM.dbClose();

            DBM.dbOpen();
            setTableExpensesDB(strSQL);
            DBM.dbClose();

            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery("select * from asset");
            int capitalAsset = 0;
            while(DBM.DB_rs.next()){
                capitalAsset = DBM.DB_rs.getInt("capital");
            }
            capitalAsset -= Integer.parseInt(txtExpensesCost.getText());
            String strExpensesUpdateSQL = "update Asset set capital=" + capitalAsset;
            DBM.DB_stmt.executeUpdate(strExpensesUpdateSQL);
            DBM.dbClose();
        } catch (Exception e) {
            System.out.println("SQLException : " + e.getMessage());
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnFilleSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilleSaveActionPerformed
        // TODO add your handling code here:
        try{
            BufferedWriter bfw = new BufferedWriter(new FileWriter("expenses.txt"));
            for(int i = 0 ; i < tableExpenses.getColumnCount() ; i++) {
                bfw.write(tableExpenses.getColumnName(i));
                bfw.write("\t");
            }

            for (int i = 0 ; i < tableExpenses.getRowCount(); i++)
            {
                bfw.newLine();
                for(int j = 0 ; j < tableExpenses.getColumnCount();j++)
                {
                    bfw.write((String)(tableExpenses.getValueAt(i,j)));
                    bfw.write("\t");;
                }
            }
            bfw.close();
            System.out.println("파일 저장 완료");
        }catch(Exception e) {
            System.out.println("FileException : " + e.getMessage());
        }
    }//GEN-LAST:event_btnFilleSaveActionPerformed

    private void rbtnExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnExpensesActionPerformed
        // TODO add your handling code here:
        Login1.User.setVisible(false);
        Login1.Salary.setVisible(false);
        Login1.Transaction.setVisible(false);
        Login1.Goods.setVisible(false);
        Login1.Order.setVisible(false);
        Login1.PS.setVisible(false);
        Login1.Expenses.setVisible(true);
    }//GEN-LAST:event_rbtnExpensesActionPerformed

    private void rbtnPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPSActionPerformed
        // TODO add your handling code here:
        Login1.User.setVisible(false);
        Login1.Salary.setVisible(false);
        Login1.Transaction.setVisible(false);
        Login1.Goods.setVisible(false);
        Login1.Order.setVisible(false);
        Login1.PS.setVisible(true);
        Login1.Expenses.setVisible(false);
    }//GEN-LAST:event_rbtnPSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ERP_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ERP_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ERP_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ERP_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User = new ERP_User();
                Salary = new ERP_Salary();
                Transaction = new ERP_Transaction();
                Goods = new ERP_Goods();
                User.setVisible(false);
                Salary.setVisible(false);
                Transaction.setVisible(false);
                Goods.setVisible(true);
                Order = new ERP_Order();
                Order.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilleSave;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnRefreshExpenses;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel labelExpensesCode;
    private javax.swing.JLabel labelExpensesCost;
    private javax.swing.JLabel labelExpensesName;
    private javax.swing.JLabel labelExpensesNo;
    private javax.swing.JLabel labelExpensesRemark;
    private javax.swing.JRadioButton rbtnEmp;
    private javax.swing.JRadioButton rbtnExpenses;
    private javax.swing.JRadioButton rbtnGoods;
    private javax.swing.JRadioButton rbtnPS;
    private javax.swing.JRadioButton rbtnSal;
    private javax.swing.JRadioButton rbtnTrans;
    private javax.swing.JTable tableExpenses;
    private javax.swing.JTextField txtExpensesAccount;
    private javax.swing.JTextField txtExpensesCode;
    private javax.swing.JTextField txtExpensesCost;
    private javax.swing.JTextField txtExpensesName;
    private javax.swing.JTextField txtExpensesRemark;
    // End of variables declaration//GEN-END:variables
}
